name: easyner_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cryptography=38.0.1
  - datasets
  - huggingface_hub
  - matplotlib-base
  - numpy
  - numpy-base
  - onnxruntime
  - openssl=1.1.1t
  - pandas
  - pillow=
  - pip
  - python=3.9
  - pytorch-cuda
  - pytorch-mutex
  - regex=2022.7.9
  - requests=2.28.1
  - seaborn=0.12.2
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tokenizers=0.11.4
  - toml=0.10.2
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tqdm
  - transformers
  - urllib3=1.26.12
  - yaml=0.2.5
  - jsonschema=4.23.0
  - pytest-benchmark=5.1.0
  - mypy
  - black
  - flake8
  - argcomplete
  - pandas-stubs
  - types-jsonschema
  - ruff
  - pip:
    - nltk==3.8.1
    - orjson
    - pubmed-parser==0.3.1
    - pytest==7.2.1
    - pytest-cov==4.0.0
    - scattertext==0.1.10
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seqeval==1.2.2
    - spacy==3.4.4
    - spacy-legacy==3.0.11
    - spacy-loggers==1.0.4
    - unidecode==1.3.6
