name: easyner_env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cryptography>=38.0.1
  - huggingface_hub
  - matplotlib-base
  - numpy
  - numpy-base
  - onnxruntime
  - pandas
  - pip
  - python==3.9
  - pytorch-cuda
  - pytorch-mutex
  - requests>=2.28.1
  - seaborn>=0.12.2
  - setuptools>=65.5.0
  - sqlite>=3.39.3
  - tokenizers>=0.11.4
  - tqdm
  - transformers
  - urllib3>=1.26.12
  - jsonschema>=4.23.0
  - pytest-benchmark>=5.1.0
  - mypy
  - black
  - argcomplete
  - pandas-stubs
  - types-jsonschema
  - ruff
  - nltk>=3.8.1
  - orjson
  - pytest>=7.2.1
  - pytest-cov>=4.0.0
  - seqeval>=1.2.2
  - spacy>=3.4.4
  - pip:
    - pubmed-parser==0.3.1
