name: easyner_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - coloredlogs=15.0.1
  - cryptography=38.0.1
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.7.99
  - cuda-gdb=11.8.86
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cycler=0.11.0
  - dbus=1.13.18
  - datasets=2.14.3
  - expat=2.4.9
  - ffmpeg=4.3
  - filelock=3.6.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - huggingface_hub=0.10.1
  - humanfriendly=10.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=7.87.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - nsight-compute=2022.3.0.22
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - onnxruntime=1.12.1
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=21.3
  - pandas=1.4.4
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - protobuf=3.20.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - seaborn=0.12.2
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.3
  - sympy=1.11.1
  - tk=8.6.12
  - tokenizers=0.11.4
  - toml=0.10.2
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.2
  - tqdm=4.64.1
  - transformers=4.24.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - attrs==22.2.0
    - blis==0.7.9
    - catalogue==2.0.8
    - click==8.1.3
    - confection==0.0.4
    - coverage==7.1.0
    - cymem==2.0.7
    - exceptiongroup==1.1.0
    - flashtext==2.7
    - fst-pso==1.8.1
    - fuzzytm==2.0.5
    - gensim==4.3.0
    - iniconfig==2.0.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - langcodes==3.3.0
    - lxml==4.9.2
    - markupsafe==2.1.1
    - miniful==0.0.6
    - murmurhash==1.0.9
    - nltk==3.8.1
    - pathy==0.10.1
    - patsy==0.5.3
    - pluggy==1.0.0
    - preshed==3.0.8
    - pubmed-parser==0.3.1
    - pydantic==1.10.4
    - pyfume==0.2.25
    - pytest==7.2.1
    - pytest-cov==4.0.0
    - scattertext==0.1.10
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seqeval==1.2.2
    - simpful==2.9.0
    - smart-open==6.3.0
    - spacy==3.4.4
    - spacy-legacy==3.0.11
    - spacy-loggers==1.0.4
    - srsly==2.4.5
    - statsmodels==0.13.5
    - thinc==8.1.7
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - typer==0.7.0
    - unidecode==1.3.6
    - wasabi==0.10.1
